### ISSUE TITLE
No services start 

### ISSUE THREAD

**Issue by GamalSebaee** [Red-Folder/Cordova-Plugin-BackgroundService#55] opened 2016-06-29 10:42 UTC
I have finished all steps of installation and build application using android studio new files  added to asset/www/ were deleted and when i run the app ,application curshed

**Comment by christocracy** [comment] 2016-06-29 10:54
This problem description is completely useless.

"It crashed".

Do you even monitor your app logs or do you just develop blindly, like wandering aimlessly through a forest with a blindfold, hoping someone benevolent open source God will find you and lead you to safety?

**Comment by Red-Folder** [comment] 2016-07-25 11:21
@GamalSebaee I assume this is duplicate of https://github.com/Red-Folder/bgs-core/issues/64

As this repo isn't actively maintained, I'll close this one and deal with the response on https://github.com/Red-Folder/bgs-core/issues/64

**Closed as completed by Red-Folder** 2016-07-25 11:22 UTC
Labels: duplicate
